//****************************************************************************
// Model: NineAxisMeasurement.qm
// File:  AttitudeGuage/Attitude.h
//
// This code has been generated by QM tool (see state-machine.com/qm).
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//****************************************************************************
//${AttitudeGuage::AttitudeGuage::Attitude.h} ................................
#ifndef _AO_ATTITUDE_H
#define _AO_ATTITUDE_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    float x;
    float y;
    float z;
} AttitudeDim;

typedef AttitudeDim Acceleration;
typedef AttitudeDim Velocity;
typedef AttitudeDim Position;

typedef AttitudeDim AngularAcc;
typedef AttitudeDim AngularRate;
typedef AttitudeDim AngularPos;

typedef AttitudeDim MagneticStrength;

struct SixAxisAttitude {
    AngularRate  angularRate;
    Acceleration linearAcc;
};

struct NineAxisAttitude {
    AngularRate  angularRate;
    Acceleration linearAcc;
    MagneticStrength magneticStrength;
};

#ifdef __cplusplus
}
#endif

#endif // _AO_ATTITUDE_H

